version: '2'
services:
    mysql:
        build: ../docker-images/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=adminpw
        ports:
        - "3306:3306"
    microservice-tasks:
        build: ../docker-images/microservice-tasks
        depends_on:
            - "mysql"
        entrypoint: ["/opt/wait_for_it.sh", "database:3306", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar", "app.jar"]
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://database/tasks

